package com.stein.myenergi.dto;

import java.util.Date;

public class DayOutput {
    // date on which this data was collected
    private Date date;
    // serial of which device this historic data is
    private String serial;

    // electricity in joules imported from the net
    private int imported;
    // electricity in joules exported to the net
    private int exported;

    // electricity in joules generated by solar panels
    private int generated;

    // electricity in joules charged into electrical vehicle
    private int charged;

    // electricity in joules consumed
    private int consumed;

    public DayOutput() {}

    public DayOutput(Date date, String serial, int imported, int exported, int generated, int charged, int consumed) {
        this.date = date;
        this.serial = serial;
        this.imported = imported;
        this.exported = exported;
        this.generated = generated;
        this.charged = charged;
        this.consumed = consumed;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getSerial() {
        return serial;
    }

    public void setSerial(String serial) {
        this.serial = serial;
    }

    public int getImported() {
        return imported;
    }

    public void setImported(int imported) {
        this.imported = imported;
    }

    public int getExported() {
        return exported;
    }

    public void setExported(int exported) {
        this.exported = exported;
    }

    public int getGenerated() {
        return generated;
    }

    public void setGenerated(int generated) {
        this.generated = generated;
    }

    public int getCharged() {
        return charged;
    }

    public void setCharged(int charged) {
        this.charged = charged;
    }

    public int getConsumed() {
        return consumed;
    }

    public void setConsumed(int consumed) {
        this.consumed = consumed;
    }
}
